### ISSUE TITLE
What dataset can be used for this schema?

### ISSUE THREAD

**Issue by reidsneo** [BISONNL/NeTEx-NL#10]
Dear maintainer,
recently I working with netherlands netex profile, but while generating data binding using this schema, I barely cannot parse the XML data set which provided on [https://data.ndovloket.nl/netex/cxx/](url) , can you give me advice which dataset should I use for netherland dataset?

Thanks!

![image](https://user-images.githubusercontent.com/12298979/117046871-cab1dc00-ad43-11eb-9506-5eb8f6b3ed6e.png)

**Comment by menn-o-v** [comment]
Hello,

As the generator of the CXX datasets I can give you some information.

The datasets do no fully comply to the European XSD. There was a limited Dutch XSD developed and in our 9.1 version I also found that this does not fit into the European XSD completely. The Dutch XSD for version 9.1 can be found here: [https://github.com/BISONNL/NeTEx-NL/archive/refs/tags/v9.1.0.1.zip](https://github.com/BISONNL/NeTEx-NL/archive/refs/tags/v9.1.0.1.zip)

Also please be aware that the delivery you were using is one of the first deliveries we did and it does have some issues, although not with the DataSource. You better use the most recent delivery.

**Comment by reidsneo** [comment]
Hi @menn-o-v  , I really appreciate for your help, a few more question :
1. Regarding the netex dataset, can the dataset in ndovloket also can be used to generate SIRI interface?, 
2. From what I know that Netex data need to be imported or parsed first, then we create kind of webservices  conform SIRI to serve netex data to consumer is that correct?
3. The public desks you mention is it the ndovloket, openov, or transdev?

Thanks!

**Comment by menn-o-v** [comment]
Hello @reidsneo,

1. The SIRI standard use is  still under development as a Dutch standard. I assume you are talking about the SIRI PT interface. I think that you may be able to generate such an interface from this data. Btw, chances are that SIRI PT will never be a implemented as a Dutch standard and that other interfaces like VM and ET will be based on the NeTEx export.
2. Yes, to extract information in any other format you will need to import the data first.
3. The public desks are ndovloket.nl of OpenGeo you are already familiar with and https://reisinformatiegroep.nl/ndovloket/ which is a of the Reisinformatiegroep. All Dutch PT companies send their information there and they pass it on or process it into other formats.

**Comment by reidsneo** [comment]
Hi @menn-o-v 
Thank you very much for the answer!, I think I managed to grasp some point for now.
I closing the issue now, again thank you!
