### ISSUE TITLE
Toevoegen optioneel attribuut Url aan Line

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#13]

**Comment by hennoit** [comment]
Lijkt me een goede uitbreiding om aan de BISON NeTEx werkgroep voor te stellen.

**Comment by skinkie** [comment]
...dan had je hem nog niet moeten goedkeuren...

**Comment by hennoit** [comment]
... dat hangt er van af wie er allemaal merges uitvoert  :-)
(het wordt dus hoog tijd om BISON procedures te bepalen omtrent github)

**Comment by hennoit** [comment]
Na goedkeuring door BISON AW verwerkt in master.
