### ISSUE TITLE
Sta srsName en srsDimension als attributen toe op pos en LineString met vaste waarden

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#15]
srsName="EPSG:28992"
srsDiwension=2

(nog beter: default waarde)

**Comment by hennoit** [comment]
Lijkt met een prima verbeteringsvoorstel om aan de BISON NeTEx groep voor te leggen. 
Voor het NL Profiel is 'fixed' correct, want we eisen inderdaad RD-coördinaten.
Impliceert een 'fixed' waarde technisch gezien dat dit ook de 'default' waarde is?

Overigens definieert men (als het goed is) in het CompositeFrame al het _DefaultLocationSystem_ voor de gehele levering (als "EPSG:28992").

**Comment by skinkie** [comment]
> Lijkt met een prima verbeteringsvoorstel om aan de BISON NeTEx groep voor te leggen. Voor het NL Profiel is 'fixed' correct, want we eisen inderdaad RD-coördinaten. Impliceert een 'fixed' waarde technisch gezien dat dit ook de 'default' waarde is?

Vind ik een goede vraag, maar dit zal vast implementatie afhankelijk zijn.
 
> Overigens definieert men (als het goed is) in het CompositeFrame al het _DefaultLocationSystem_ voor de gehele levering (als "EPSG:28992").

Correct. Dus je kunt op alle pos elementen srsName toepassen, maar dan moet je dat natuurlijk _wel_ doen.
