### ISSUE TITLE
Zou Monitored (net als upstream) een default waarde moeten hebben?

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#20]

**Comment by hennoit** [comment]
Volgens de huidige omschrijving in het NL Profiel kun je _Monitored_ bij (Template)ServiceJourney en DeadRun gebruiken om de waarde op TimetableFrame of Line niveau te overschrijven - en moet je het anders niet invullen. Dus is een defaultwaarde hier NIET zinvol, want dan overschrijf je ALTIJD de waarde van het frame / de lijn...

Op TimetableFrame heeft _Monitored_ inhet NL Profiel wel een defaultwaarde (true).
En op Line is het in het NL Profiel een verplicht veld.

**Comment by skinkie** [comment]
Zinnig argument om dit niet aan te passen :-)
