### ISSUE TITLE
vehicleTypes is required, but VehicleTypeRef has minOccurs=0

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#21]

**Comment by hennoit** [comment]
De BISON NeTEx werkgroep heeft in november 2020 besloten om de VehicleTypes verplicht te maken, omdat ze nodig zijn voor de toegankelijkheidsinformatie. De verwijzing VehicleTypeRef is optioneel omdat je de koppeling van een rit aan een voertuigtype op twee plekken kunt leggen, nl. op het Block of op de individuele VehicleJourney.
