### ISSUE TITLE
TopographicPlaceView is beschikbaar in StopArea maar niet in ScheduledStopPoint

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#23]

**Comment by hennoit** [comment]
Klopt. We gebruiken het tot nog toe alleen om een equivalent te hebben van het KV1 veld _USRSTAR.Town_. 
Toevoegen op ScheduledStopPoint zou dus een (te bespreken, zinvolle) _enhancement_ kunnen zijn.
