### ISSUE TITLE
TimingLink FromPointRef/ToPointRef heeft geen nameOfRefClass

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#27]
TimingLink FromPointRef en ToPointRef zijn van het type TimingPointRefStructure. Gezien we in het Nederlandse profiel verwijzen naar een ScheduledStopPoint (en hiervoor in dit geval geen ServiceLink gebruiken) is de verwijzing feitelijk naar een andere klasse. Ik vind het vanzelfsprekend dat hiervoor nameOfRefClass gebruikt dient te worden in het geval van een ScheduledStopPoint, voor de verwijzing naar een TimingPoint zou volstaan kunnen worden zonder deze toevoeging.

**Comment by hennoit** [comment]
Maakt de volgende xsd versie wel niet-compatible met de vorige... en de bestanden vermoedelijk nog weer groter...
Laten we dit ook maar in de groep gooien in januari.

**Comment by skinkie** [comment]
Hoe kan een _optioneel_ element niet compatible worden? Daarbij deze XSD is ter _controle_, er zit geen enkele compatibiliteit aan vast. Gelukkig zorgt gzip compressie er voor dat het op de omvang geen invloed heeft.
