### ISSUE TITLE
Lijnleveringen

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#40]
Binnen EPIP wordt onderscheid gemaakt tussen volledige leveringen en lijnleveringen op een CompositeFrame, voor EPIP geldt dan een EU_PI_LINE_OFFER. In het Nederlandse profiel (is er op de bestandsnaam na en het tellen van 'lines') geen identificatie mogelijk.

**Comment by menn-o-v** [comment]
Binnen het NL profiel wordt de lijnlevering herkent aan de VersionType 'point':
			<versions>
				<Version id="CXX:VS:CXX-202203275" version="202203275">
					<StartDate>2022-11-06T00:00:00Z</StartDate>
					<EndDate>2022-12-10T00:00:00Z</EndDate>
					<Description>CXX 2022 vanaf 06-11-2022_F100</Description>
					<VersionType>point</VersionType>
					<DerivedFromVersionRef version="202203244" ref="CXX:VS:CXX-202203244"/>
				</Version>
			</versions>

**Comment by hilcokats** [comment]
Lijnleveringen zijn verwijderd uit het NL-profiel. Issue closed.
