### ISSUE TITLE
ServiceJourneyPatternRef en TimeDemandTypeRef met versie worden niet gevonden

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#64]

**Comment by hilcokats** [comment]
Kun je deze nader toelichten?

**Comment by skinkie** [comment]
Volgens mij was het probleem dat als je een id als version attribuut hebt op een ServiceJourneyPatternRef of TimeDemandTypeRef dat constraint validatie niet meer werkt.

**Comment by hilcokats** [comment]
Ik kan deze echt niet plaatsen. Speelt dit nog steeds? Zo ja, heb je een voorbeeld + validatie-foutmelding?

**Comment by skinkie** [comment]
Ik ook niet (meer).
