### ISSUE TITLE
Ferry vs Water

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#69]
Gezien ik zelf de fout heb gemaakt. Weten wij het intrinsieke verschil tussen TransportMode/VehicleMode WATER vs FERRY? De laatste zit niet in dit schema, waar DOVA weer over struikelt.

**Comment by Joostb61** [comment]
Het EU model kent alleen VehicleMode WATER. In WaterSubModeEnum komen wel verschillende typen Ferries (localCarFerry, localPassengerFerry etc., maar niet 'FERRY' . In het NL-profiel gebruiken we de volgende waarden voor WaterSubmode: 
highSpeedPassengerService  Snelboot
scheduledFerry                        Veerboot
shuttleFerryService                  Veerpont
riverBus                                     Waterbus
localPassngerFerry                  Watertaxi
Interpretatie en vertaling tbv NL reisinformatie is op basis van best effort.

**Comment by skinkie** [comment]
@Joostb61 dit antwoord klopt niet.

https://github.com/NeTEx-CEN/NeTEx/blob/master/xsd/netex_framework/netex_reusableComponents/netex_mode_support.xsd#L115

**Comment by Joostb61** [comment]
Denk dat ferry op GitHub later aan de enum is toegevoegd, in de documentatie komt deze nog niet terug. Vind de uitbreiding  van VehicleMode met ferry niet zo gelukkig omdat de onderverdeling naar TransportSubMode 'Water' daar niet op aansluit. Ook omdat het niet gedocumenteerd is, anders dan de naam, is niet duidelijk hoe 'ferry' te gebruiken.

**Comment by skinkie** [comment]
@Joostb61 in mijn optiek sluit air, rail, water op elkaar aan; en bus, metro, tram, ferry op elkaar. Maar daar tussen zit dus de discrepantie.
