### ISSUE TITLE
AdministrativeZone

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#8]
Our documentation states that we support a AdministrativeZone. Should it be TransportAdministrativeZone instead or should upstream be fixed?

```xml
                <!-- =====TransportAdministrativeZone Key ========================== -->
                <xsd:keyref name="TransportAdministrativeZone_KeyRef" refer="netex:TransportAdministrativeZone_AnyVersionedKey">
                        <xsd:selector xpath=".//netex:TransportAdministrativeZoneRef |.//netex:ResponsibilityRoleAssignment/netex:ResponsibleAreaRef"/>
                        <xsd:field xpath="@ref"/>
                        <xsd:field xpath="@version"/>
                </xsd:keyref>
```

**Comment by hennoit** [comment]
Volgens het officiële NeTEx document bevat ResponsibleAreaRef een AdministrativeZoneRef (een verwijzing naar een ADMINISTRATIVE ZONE), dus niet expliciet een _Transport_ AdministrativeZone. Vanuit dat oogpunt is de constraint dus te sterk. Ook gezien de mogelijk brede toepassing van ResponsibilityRoleAssignment lijkt mij de beperking tot _Transport_ AdministrativeZone niet handig.
In de praktijk kan het echter misschien gemakkelijker zijn om het NL Profiel aan te passen dan de EU standaard (hoewel alleen het xsd laten aanpassen nog te proberen valt).
Het enige extra in TAZ ten opzichte van AZ zijn de VehicleModes. Die zijn echter optioneel, dus dan hoeft er in het NL Profiel inhoudelijk verder niets te veranderen behalve de objectnaam.

**Comment by hennoit** [comment]
In the newest versions of the Dutch NeTEx Profile (9.2.x) the text has been changed to expect a reference to a _Transport_ AdministrativeZone in ResponsibleAreaRef.
So this issue can be closed.
