### ISSUE TITLE
VehicleAccessFacilityList neemt verkeerde enumeratie over

### ISSUE THREAD

**Issue by skinkie** [BISONNL/NeTEx-NL#81]
Wat is dit nu weer?

```xml
<xsd:element name="VehicleAccessFacilityList">
        <xsd:simpleType>
                <xsd:list itemType="AccessFacilityEnumeration"/>
                <!--    <xsd:list itemType="VehicleAccessFacilityEnumeration"/> -->
        </xsd:simpleType>
</xsd:element>
```

**Comment by Joostb61** [comment]
Is dit een gevolg van marge van EPIAP en NeTEx?
In de NL documentatie staat nu als opmerking bij VehicleAccessFacilityList: logischer zou zijn VehicleAccesFacilityEnum, maar dat zit nog fout in de standaard. Deze enum is breder, maar omvat wel de voor NL gewenste waarden (maar 'ramp' ipv 'manualRamp').

**Comment by skinkie** [comment]
Welke waarden zouden voor Nederland hebben ontbroken?

```
        <xsd:simpleType name="VehicleAccessFacilityEnumeration">
                <xsd:annotation>
                        <xsd:documentation>Allowed values for Vehicle Access Facility. NB. These are the  properties of access to a VEHICLE. +1.1</xsd:documentation>
                </xsd:annotation>
                <xsd:restriction base="xsd:NMTOKEN">
                        <xsd:enumeration value="unknown"/>
                        <xsd:enumeration value="wheelchairLift"/>
                        <xsd:enumeration value="manualRamp"/>
                        <xsd:enumeration value="automaticRamp"/>
                        <xsd:enumeration value="steps"/>
                        <xsd:enumeration value="slidingStep"/>
                        <xsd:enumeration value="narrowEntrance"/>
                        <xsd:enumeration value="validator"/>
                </xsd:restriction>
        </xsd:simpleType>
```

**Comment by Joostb61** [comment]
In de AccessFacilityEnumeration stonden de faciliteiten aan de wal zijde en aan de voertuigzijde door elkaar. 

unknown
lift
wheelchairLift
escalator
travelator
ramp
automaticRamp
steps
stairs
slidingStep
shuttle
narrowEntrance
barrier
lowFloorAccess
validator

Bovendien was er geen onderscheid tussen ramp (niet bekend of het handmatig of automatisch is) en manualRamp, cq automaticRamp. 

In de CEN XSD kon VehicleAccessFacilityEnumeration nog niet worden gebruikt, sinds de merge van EPIAP in NeTEx van vorige week kan dit wel, 

Groet, 


Joost
